# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

def cp0011(name, username, email, password):
    try:
        driver = webdriver.Chrome()
        driver.implicitly_wait(10)
        driver.get("https://tucan.toolsincloud.net/")
        driver.set_window_size(974, 1040)
        driver.find_element(By.ID, "auto").click()
        driver.find_element(By.ID, "exampleInputEmail1").click()
        driver.find_element(By.ID, "exampleInputEmail1").send_keys(name)
        driver.find_element(By.NAME, "username").click()
        driver.find_element(By.NAME, "username").send_keys(username)
        driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(4) > #exampleInputEmail1").click()
        driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(4) > #exampleInputEmail1").send_keys(email)
        driver.find_element(By.ID, "exampleInputPassword1").click()
        driver.find_element(By.ID, "exampleInputPassword1").send_keys(password)
        driver.find_element(By.NAME, "signup").click()
        time.sleep(2)
        driver.refresh()
        elements = driver.find_elements(By.CSS_SELECTOR, "#whathappen > .container")
        assert len(elements) > 0
        driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
        driver.quit()
        print("Test CP0011: Aprobado")
        return True
    except:
        print("Test CP0011: Denegado")
        return False
def cp0012(name, username, email, password):
    try:
        driver = webdriver.Chrome()
        driver.implicitly_wait(10)
        driver.get("https://tucan.toolsincloud.net/")
        driver.set_window_size(814, 867)
        driver.find_element(By.ID, "auto").click()
        driver.find_element(By.ID, "exampleInputEmail1").click()
        driver.find_element(By.ID, "exampleInputEmail1").send_keys(name)
        driver.find_element(By.NAME, "username").click()
        driver.find_element(By.NAME, "username").send_keys(username)
        driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(4) > #exampleInputEmail1").click()
        driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(4) > #exampleInputEmail1").send_keys(email)
        driver.find_element(By.ID, "exampleInputPassword1").click()
        driver.find_element(By.ID, "exampleInputPassword1").send_keys(password)
        driver.find_element(By.NAME, "signup").click()
        assert driver.find_element(By.CSS_SELECTOR, ".text-center:nth-child(1)").text == "This email is already use"
        driver.quit()
        print("Test CP0012: Aprobado")
        return True
    except:
        print("Test CP0012: Denegado")
        return False
def cp0021(name, username, email, password):
    try:
        driver = webdriver.Chrome()
        driver.implicitly_wait(10)
        driver.get("https://tucan.toolsincloud.net/")
        driver.set_window_size(1050, 840)
        driver.find_element(By.NAME, "email").click()
        driver.find_element(By.NAME, "email").send_keys(email)
        driver.find_element(By.NAME, "password").click()
        driver.find_element(By.NAME, "password").send_keys(password)
        driver.find_element(By.NAME, "login").click()
        driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
        elements = driver.find_elements(By.CSS_SELECTOR, ".login-bird")
        assert len(elements) > 0
        driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
        driver.quit()
        print("Test CP0021: Aprobado")
        return True
    except:
        print("Test CP0021: Denegado")
        return False
def cp0022(name, username, email, password):
    try:
        driver = webdriver.Chrome()
        driver.implicitly_wait(10)
        driver.get("https://tucan.toolsincloud.net/")
        driver.set_window_size(770, 867)
        driver.find_element(By.NAME, "email").click()
        driver.find_element(By.NAME, "email").send_keys(email)
        driver.find_element(By.NAME, "password").click()
        driver.find_element(By.NAME, "password").send_keys("Holamundo")
        driver.find_element(By.NAME, "login").click()
        elements = driver.find_elements(By.CSS_SELECTOR, ".span-fp-error")
        assert len(elements) > 0
        driver.quit()
        print("Test CP0022: Aprobado")
        return True
    except:
        print("Test CP0022: Denegado")
        return False
def cp0031(name, username, email, password):
    try:
        driver = webdriver.Chrome()
        driver.implicitly_wait(10)
        driver.get("https://tucan.toolsincloud.net/")
        driver.set_window_size(784, 816)
        driver.find_element(By.NAME, "email").click()
        driver.find_element(By.NAME, "email").send_keys(email)
        driver.find_element(By.NAME, "password").send_keys(password)
        driver.find_element(By.NAME, "login").click()
        driver.find_element(By.NAME, "status").click()
        driver.find_element(By.NAME, "status").send_keys("Mensaje de prueba")
        driver.find_element(By.ID, "tweet-input").click()
        assert driver.find_element(By.CSS_SELECTOR, "css= a > span").text == "Mensaje de prueba"
        driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
        driver.quit()
        print("Test CP0031: Aprobado")
        return True
    except:
        print("Test CP0031: Denegado")
        return False
def cp0032(name, username, email, password):
    try:
        driver = webdriver.Chrome()
        driver.implicitly_wait(10)
        driver.get("https://tucan.toolsincloud.net/home.php")
        driver.set_window_size(770, 867)
        driver.find_element(By.NAME, "email").click()
        driver.find_element(By.NAME, "email").send_keys(email)
        driver.find_element(By.NAME, "password").click()
        driver.find_element(By.NAME, "password").send_keys(password)
        driver.find_element(By.NAME, "login").click()
        driver.find_element(By.NAME, "status").click()
        driver.find_element(By.NAME, "status").send_keys("Hola, este es el mensaje que supera los 140 caracteres, lo que no está permitido dentro de la red social, ya que solo nos permite 140, ¿aburrido verdad?")
        driver.find_element(By.ID, "tweet-input").click()
        elements = driver.find_elements(By.CSS_SELECTOR, ".item2-pair")
        assert len(elements) > 0
        driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
        driver.quit()
        print("Test CP0032: Aprobado")
        return True
    except:
        print("Test CP0032: Denegado")
        return False
def cp0041(name, username, email, password):
    try:
        driver = webdriver.Chrome()
        driver.implicitly_wait(10)
        driver.get("https://tucan.toolsincloud.net/home.php")
        driver.set_window_size(770, 867)
        driver.find_element(By.NAME, "email").click()
        driver.find_element(By.NAME, "email").send_keys(email)
        driver.find_element(By.NAME, "password").click()
        driver.find_element(By.NAME, "password").send_keys(password)
        driver.find_element(By.NAME, "login").click()
        driver.find_element(By.CSS_SELECTOR, ".box-tweet:nth-child(3) .grid-box-reaction:nth-child(2) .fas").click()
        element = driver.find_element(By.CSS_SELECTOR, ".box-tweet:nth-child(6) > .grid-tweet > a")
        actions = ActionChains(driver)
        actions.move_to_element(element).perform()
        element = driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(driver)
        actions.move_to_element(element, 0, 0).perform()
        driver.find_element(By.CSS_SELECTOR, ".retweet-i .option-text").click()
        elements = driver.find_elements(By.CSS_SELECTOR, ".box-tweet:nth-child(3) .hover-reaction-retweet")
        assert len(elements) > 0
        driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
        driver.quit()
        print("Test CP0041: Aprobado")
        return True
    except:
        print("Test CP0041: Denegado")
        return False
def cp0042(name, username, email, password):
    try:
        driver = webdriver.Chrome()
        driver.implicitly_wait(10)
        driver.get("https://tucan.toolsincloud.net/home.php")
        driver.set_window_size(784, 816)
        driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
        driver.find_element(By.NAME, "email").click()
        driver.find_element(By.NAME, "email").send_keys(email)
        driver.find_element(By.NAME, "password").send_keys(password)
        driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
        driver.find_element(By.CSS_SELECTOR, ".grid-tweet:nth-child(3) .hover-reaction-retweet > .fas").click()
        driver.find_element(By.CSS_SELECTOR, ".retweet-i .option-text").click()
        elements = driver.find_elements(By.CSS_SELECTOR, ".box-tweet:nth-child(3) .hover-reaction-retweet")
        assert len(elements) == 0
        driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
        driver.quit()
        print("Test CP0042: Aprobado")
        return True
    except:
        print("Test CP0042: Denegado")
        return False
def cp0051(name, username, email, password):
    try:
        driver = webdriver.Chrome()
        driver.implicitly_wait(10)
        driver.get("https://tucan.toolsincloud.net/home.php")
        driver.set_window_size(770, 867)
        driver.find_element(By.NAME, "email").click()
        driver.find_element(By.NAME, "email").send_keys(email)
        driver.find_element(By.NAME, "password").click()
        driver.find_element(By.NAME, "password").send_keys(password)
        driver.find_element(By.NAME, "login").click()
        driver.find_element(By.CSS_SELECTOR, ".grid-tweet:nth-child(3) .comment").click()
        driver.find_element(By.CSS_SELECTOR, ".popupComment:nth-child(20) .retweet-msg").click()
        driver.find_element(By.CSS_SELECTOR, ".popupComment:nth-child(20) .retweet-msg").send_keys("Hola")
        driver.find_element(By.CSS_SELECTOR, ".popupComment:nth-child(20) .comment-it").click()
        elements = driver.find_elements(By.CSS_SELECTOR, ".grid-tweet:first-child .comment")
        assert len(elements) > 0
        driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
        driver.quit()
        print("Test CP0051: Aprobado")
        return True
    except:
        print("Test CP0051: Denegado")
        return False
def cp0052(name, username, email, password):
    coment = "La inteligencia artificial está transformando la medicina, el entretenimiento, la educación y la industria, pero también plantea desafíos éticos y sociales."
    try:
        driver = webdriver.Chrome()
        driver.implicitly_wait(10)
        driver.get("https://tucan.toolsincloud.net/")
        driver.set_window_size(784, 816)
        driver.find_element(By.NAME, "email").click()
        driver.find_element(By.NAME, "email").send_keys(email)
        driver.find_element(By.NAME, "password").send_keys(password)
        driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
        driver.find_element(By.CSS_SELECTOR, ".box-tweet:nth-child(3) > a > span").click()
        driver.find_element(By.CSS_SELECTOR, ".comment p").click()
        driver.find_element(By.CSS_SELECTOR, ".retweet-msg").click()
        driver.find_element(By.CSS_SELECTOR, ".retweet-msg").send_keys(coment)
        driver.find_element(By.CSS_SELECTOR, ".comment-it").click()
        assert driver.find_element(By.CSS_SELECTOR,
                                        ".box-comment:nth-child(1) p:nth-child(2)").text == coment[:136]
        driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
        driver.quit()
        print("Test CP0052: Aprobado")
        return True
    except:
        print("Test CP0052: Denegado")
        return False
def cp0061(name, username, email, password):
    try:
        driver = webdriver.Chrome()
        driver.implicitly_wait(10)
        driver.get("https://tucan.toolsincloud.net/home.php")
        driver.set_window_size(770, 860)
        driver.find_element(By.NAME, "email").click()
        driver.find_element(By.NAME, "email").send_keys(email)
        driver.find_element(By.NAME, "password").click()
        driver.find_element(By.NAME, "password").send_keys(password)
        driver.find_element(By.NAME, "login").click()
        driver.find_element(By.CSS_SELECTOR, ".grid-tweet:nth-child(3) .hover-reaction-like").click()
        elements = driver.find_elements(By.CSS_SELECTOR, ".grid-tweet:nth-child(3) .hover-reaction-like")
        assert len(elements) > 0
        driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
        driver.quit()
        print("Test CP0061: Aprobado")
        return True
    except:
        print("Test CP0061: Denegado")
def cp0062(name, username, email, password):
    try:
        driver = webdriver.Chrome()
        driver.implicitly_wait(10)
        driver.get("https://tucan.toolsincloud.net/")
        driver.set_window_size(784, 816)
        driver.find_element(By.NAME, "email").click()
        driver.find_element(By.NAME, "email").send_keys(email)
        driver.find_element(By.NAME, "password").send_keys(password)
        driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
        driver.find_element(By.CSS_SELECTOR, ".box-tweet:nth-child(3) .fa-heart").click()
        driver.find_element(By.CSS_SELECTOR, ".box-tweet:nth-child(3) .fa-heart").click()
        element = driver.find_element(By.CSS_SELECTOR, ".box-tweet:nth-child(3) .fa-heart")
        actions = ActionChains(driver)
        actions.double_click(element).perform()
        assert driver.find_element(By.CSS_SELECTOR, ".unlike-btn > .mt-counter").text == "1"
        driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
        driver.quit()
        print("Test CP0062: Aprobado")
        return True
    except:
        print("Test CP0062: Denegado")
        return False
def cp0071(name, username, email, password):
    try:
        driver = webdriver.Chrome()
        driver.implicitly_wait(10)
        driver.get("https://tucan.toolsincloud.net/home.php/home.php")
        driver.set_window_size(972, 816)
        driver.find_element(By.NAME, "email").click()
        driver.find_element(By.NAME, "email").send_keys(email)
        driver.find_element(By.NAME, "password").click()
        driver.find_element(By.NAME, "password").send_keys(password)
        driver.find_element(By.NAME, "login").click()
        driver.find_element(By.CSS_SELECTOR, ".form-control").click()
        driver.find_element(By.CSS_SELECTOR, ".form-control").send_keys("Cristhian")
        driver.find_element(By.LINK_TEXT, "Cristhian Tapiero").click()
        assert driver.find_element(By.CSS_SELECTOR, "h4").text == "Cristhian Tapiero"
        driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
        driver.quit()
        print("Test CP0071: Aprobado")
        return True
    except:
        print("Test CP0071: Denegado")
        return False
def cp0072(name, username, email, password):
    try:
        driver = webdriver.Chrome()
        driver.implicitly_wait(10)
        driver.get("https://tucan.toolsincloud.net/home.php/")
        driver.set_window_size(972, 816)
        driver.find_element(By.NAME, "email").click()
        driver.find_element(By.NAME, "email").send_keys(email)
        driver.find_element(By.NAME, "password").send_keys(password)
        driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
        driver.find_element(By.CSS_SELECTOR, ".wrapper-right").click()
        driver.find_element(By.CSS_SELECTOR, ".form-control").click()
        driver.find_element(By.CSS_SELECTOR, ".form-control").send_keys("@Cristhian")
        elements = driver.find_elements(By.CSS_SELECTOR, "li:nth-child(2) > .nav-right-down-inner")
        assert len(elements) == 0
        driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
        driver.quit()
        print("Test CP0072: Aprobado")
        return True
    except:
        print("Test CP0072: Denegado")
        return False
def cp0081(name, username, email, password):
    try:
        driver = webdriver.Chrome()
        driver.implicitly_wait(10)
        driver.get("https://tucan.toolsincloud.net/home.php/")
        driver.set_window_size(972, 816)
        driver.find_element(By.NAME, "email").click()
        driver.find_element(By.NAME, "email").send_keys(email)
        driver.find_element(By.NAME, "password").send_keys(password)
        driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
        driver.find_element(By.CSS_SELECTOR, ".grid-share:nth-child(2) .follow-btn").click()
        assert driver.find_element(By.CSS_SELECTOR, ".following").text == "Following"
        driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
        driver.quit()
        print("Test CP0081: Aprobado")
        return True
    except:
        print("Test CP0081: Denegado")
        return False
def cp0082(name, username, email, password):
    try:
        driver = webdriver.Chrome()
        driver.implicitly_wait(10)
        driver.get("https://tucan.toolsincloud.net/home.php/")
        driver.set_window_size(972, 816)
        driver.find_element(By.NAME, "email").click()
        driver.find_element(By.NAME, "email").send_keys(email)
        driver.find_element(By.NAME, "password").send_keys(password)
        driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
        driver.find_element(By.CSS_SELECTOR, ".grid-share:nth-child(2) .follow-btn").click()
        assert driver.find_element(By.CSS_SELECTOR, ".following").text == "Following"
        driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
        driver.quit()
        print("Test CP0081: Aprobado")
        return True
    except:
        print("Test CP0081: Denegado")
        return False
def cp0091(name, username, email, password):
    try:
        driver = webdriver.Chrome()
        driver.implicitly_wait(10)
        driver.get("https://tucan.toolsincloud.net/home.php/")
        driver.set_window_size(972, 816)
        driver.find_element(By.NAME, "email").click()
        driver.find_element(By.NAME, "email").send_keys(email)
        driver.find_element(By.NAME, "password").send_keys(password)
        driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
        driver.find_element(By.CSS_SELECTOR, ".position-relative:nth-child(1) > img").click()
        assert driver.find_element(By.CSS_SELECTOR, ".home-name").text == "Notifications"
        driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
        driver.quit()
        print("Test CP0091: Aprobado")
        return True
    except:
        print("Test CP0091: Denegado")
        return False
def cp0092(name, username, email, password):
        try:
            driver = webdriver.Chrome()
            driver.implicitly_wait(10)
            driver.get("https://tucan.toolsincloud.net/notification.php")
            driver.set_window_size(972, 816)
            elements = driver.find_elements(By.CSS_SELECTOR, ".twt-login")
            assert len(elements) > 0
            driver.quit()
            print("Test CP0092: Aprobado")
            return True
        except:
            print("Test CP0092: Denegado")
            return False
def cp0101(name, username, email, password):
    try:
        driver = webdriver.Chrome()
        driver.implicitly_wait(10)
        driver.get("https://tucan.toolsincloud.net/home.php/")
        driver.set_window_size(972, 816)
        driver.find_element(By.NAME, "email").click()
        driver.find_element(By.NAME, "email").send_keys(email)
        driver.find_element(By.NAME, "password").send_keys(password)
        driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
        driver.find_element(By.CSS_SELECTOR, ".grid-sidebar:nth-child(7) img").click()
        driver.find_element(By.CSS_SELECTOR, ".count-following-i").click()
        elements = driver.find_elements(By.CSS_SELECTOR, ".retweet-popup-body-wrap")
        assert len(elements) > 0
        driver.find_element(By.CSS_SELECTOR, ".fa").click()
        driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
        driver.quit()
        print("Test CP0101: Aprobado")
        return True
    except:
        print("Test CP0101: Denegado")
        return False
def cp0102(name, username, email, password ):
    try:
        driver = webdriver.Chrome()
        driver.implicitly_wait(10)
        driver.get("https://tucan.toolsincloud.net/home.php/home.php")
        driver.set_window_size(972, 816)
        elements = driver.find_elements(By.CSS_SELECTOR, ".twt-login")
        assert len(elements) > 0
        driver.quit()
        print("Test CP0102: Aprobado")
        return True
    except:
        print("Test CP0102: Denegado")
        return False
def cp0111(name, username, email, password):
    try:
        driver = webdriver.Chrome()
        driver.implicitly_wait(10)
        driver.get("https://tucan.toolsincloud.net/")
        driver.set_window_size(784, 816)
        driver.find_element(By.NAME, "email").click()
        driver.find_element(By.NAME, "email").send_keys(email)
        driver.find_element(By.NAME, "password").send_keys(password)
        driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
        driver.find_element(By.CSS_SELECTOR, ".grid-sidebar:nth-child(7) img").click()
        driver.find_element(By.CSS_SELECTOR, ".home-edit-button").click()
        driver.find_element(By.NAME, "bio").click()
        driver.find_element(By.NAME, "bio").send_keys("Hola")
        driver.find_element(By.NAME, "update").click()
        elements = driver.find_elements(By.CSS_SELECTOR, ".bio")
        assert len(elements) > 0
        driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
        driver.quit()
        print("Test CP0111: Aprobado")
        return True
    except:
        print("Test CP0111: Denegado")
        return False
def cp0112(name, username, email, password):
    coment = "La inteligencia artificial está transformando la medicina, el entretenimiento, la educación y la industria, pero también plantea desafíos éticos y sociales."
    try:
        driver = webdriver.Chrome()
        driver.implicitly_wait(10)
        driver.get("https://tucan.toolsincloud.net/")
        driver.set_window_size(784, 816)
        driver.find_element(By.NAME, "email").click()
        driver.find_element(By.NAME, "email").send_keys(email)
        driver.find_element(By.NAME, "password").send_keys(password)
        driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
        driver.find_element(By.CSS_SELECTOR, ".grid-sidebar:nth-child(7) img").click()
        driver.find_element(By.CSS_SELECTOR, ".home-edit-button").click()
        driver.find_element(By.NAME, "bio").click()
        driver.find_element(By.NAME, "bio").send_keys(coment)
        driver.find_element(By.NAME, "update").click()
        elements = driver.find_elements(By.CSS_SELECTOR, ".alert")
        assert len(elements) > 0
        driver.find_element(By.NAME, "update").click()
        driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
        driver.quit()
        print("Test CP0112: Aprobado")
        return True
    except:
        print("Test CP0112: Denegado")
        return False
def cp0121(name, username, email, password):
    try:
        modified_email = email[:email.index('@')] + '1' + email[email.index('@'):]
        driver = webdriver.Chrome()
        driver.implicitly_wait(10)
        driver.get("https://tucan.toolsincloud.net/index.php")
        driver.set_window_size(974, 816)
        driver.find_element(By.NAME, "email").click()
        driver.find_element(By.NAME, "email").send_keys(email)
        driver.find_element(By.NAME, "password").send_keys(password)
        driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
        driver.find_element(By.CSS_SELECTOR, ".grid-sidebar:nth-child(9) img").click()
        driver.find_element(By.ID, "exampleInputEmail1").click()
        driver.find_element(By.ID, "exampleInputEmail1").send_keys(modified_email)
        driver.find_element(By.NAME, "submit").click()
        driver.find_element(By.ID, "exampleInputEmail1").click()
        driver.find_element(By.ID, "exampleInputEmail1").send_keys(email)
        driver.find_element(By.NAME, "submit").click()
        driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
        driver.quit()
        print("Test CP0121: Aprobado")
        return True
    except:
        print("Test CP0121: Denegado")
        return False
def cp0122(name, username, email, password):
    try:
        driver = webdriver.Chrome()
        driver.implicitly_wait(10)
        driver.get("https://tucan.toolsincloud.net/")
        driver.set_window_size(1552, 832)
        driver.find_element(By.NAME, "email").click()
        driver.find_element(By.NAME, "email").send_keys(email)
        driver.find_element(By.NAME, "password").click()
        driver.find_element(By.NAME, "password").send_keys(password)
        driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
        driver.find_element(By.CSS_SELECTOR, ".grid-sidebar:nth-child(9) strong").click()
        emailChangeInput = driver.find_element(By.ID, "exampleInputEmail1")
        emailChangeInput.click()
        driver.execute_script("arguments[0].setAttribute('type', 'text')", emailChangeInput)
        driver.find_element(By.ID, "exampleInputEmail1").send_keys("cristapi56")
        driver.find_element(By.NAME, "submit").click()
        assert driver.find_element(By.CSS_SELECTOR, ".alert > .text-center").text == "email is not valid"
        driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
        driver.quit()
        print("Test CP0121: Aprobado")
        return True
    except:
        print("Test CP0121: Denegado")
        return False
